@startuml

package Mapbender <<Frame>> {

  package QueryBuild <<Frame>>{
    package Element <<Frame>>{
      class QueryBuilder <extends Element>{
         __ API __
         + executeQuery(int queryId): array
      }
    }
  }
}
@enduml
